version: "3"
services:
  httpd:
    image: httpd:2.4.39
    command: ["tail", "-f", "--retry", "/usr/local/apache2/logs/error_log"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - docker-net
    volumes:
      - "{{ environment.dockerRootPath }}/distributions/mod_dispatcher.so:/usr/local/apache2/modules/mod_dispatcher.so"
      - "{{ environment.dockerRootPath }}/httpd/cache:/opt/aem/dispatcher/cache"
      - "{{ environment.dockerRootPath }}/httpd/logs:/usr/local/apache2/logs"
      - "{{ environment.dockerConfigPath }}/httpd/conf:/usr/local/apache2/conf"
    {% if (environment.dockerRuntime.name == 'toolbox') %}
    extra_hosts:
      - "host.docker.internal:10.0.2.2"
    {% endif %}
  knotx:
    image: knotx/knotx:2.0.0-RC1
    command: ["knotx", "run-knotx"]
    volumes:
      - "{{ environment.dockerConfigPath }}/knotx/conf:/usr/local/knotx/conf"
      - "{{ environment.dockerRootPath }}/knotx/logs:/var/log/knotx"
    ports:
      - "8092:8092"
    networks:
      - docker-net
networks:
  docker-net:
