version: "3"
services:
  httpd:
    image: httpd:2.4.39
    command: ["tail", "-f", "--retry", "/usr/local/apache2/logs/error_log"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - docker-net

    volumes:
      - "{{ environment.dockerRootPath }}/distributions/mod_dispatcher.so:/usr/local/apache2/modules/mod_dispatcher.so"
      - "{{ environment.dockerRootPath }}/httpd/cache:/opt/aem/dispatcher/cache"
      - "{{ environment.dockerRootPath }}/httpd/logs:/usr/local/apache2/logs"
      - "{{ environment.dockerConfigPath }}/httpd/conf:/usr/local/apache2/conf"

    {% if (environment.dockerType == 'TOOLBOX') %}
    extra_hosts:
      - "host.docker.internal:10.0.2.2"
    {% endif %}
networks:
  docker-net:
